name: mesa-core20
base: core20
adopt-info: mesa
summary: mesa libraries for core20 snaps
description: |
  A content snap containing the mesa libraries and drivers for core 20
compression: lzo

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

parts:
  mesa:
    plugin: nil
    override-pull:
      snapcraftctl set-version `LANG=C apt-cache policy libgl1-mesa-dri | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all
      - libegl1
    organize:
      'usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri/*': egl/dri/
      'usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/*.so*': egl/lib/
    prime:
      - egl/lib
      - egl/dri

slots:
  graphics-core20:
    interface: content
    read:
      - egl
